substitutions:
  name: zb-gw03-coordinator
  device_description: "ZB-GW03 eWeLink Ethernet Zigbee Gateway based Zigbee Coordinator"

packages:
  device_base:  !include  packages/core.yaml
  ethernet: !include  packages/ethernet.yaml
  status_led: !include  packages/status_led.yaml
  mdns: !include  packages/mdns.yaml
  dashboard: !include packages/dashboard.yaml

