binary_sensor:
  - platform: gpio
    name: "${name} Zigbee Reset Button"
    pin:
      number: GPIO34
      inverted: true
    on_press:
      - switch.turn_off: download_mode
      - button.press: zigbee_reset

